site_name: Despliegue de aplicaciones web
site_url: https://mydomain.org/mysite
theme:
  name: material
  features:
    - highlight
  
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - pymdownx.highlight:
      linenums: true

nav:
  - 'Tema 4': 
    - 'Práctica 4.1': 'index.md'