site_name: Despliegue de aplicaciones web
site_url: https://mydomain.org/mysite
theme:
  name: material
  
markdown_extensions:
  - admonition
  - codehilite

nav:
  - 'Tema 4': 
    - 'Práctica 4.1': 'practica4-1.md'